<?php
require_once __DIR__.'/config/db.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST' && verify_csrf($_POST['csrf']??null)){
  if(!is_logged_in()){flash('error','Please login before placing your order.');redirect('login.php?return=cart/');}
  $items=json_decode($_POST['cart_json']??'[]',true) ?: []; $address=(int)($_POST['address_id']??0); $coupon=trim($_POST['coupon']??''); $payment=in_array($_POST['payment_method']??'cod',['cod','razorpay'],true)?$_POST['payment_method']:'cod'; $pointsUsed=max(0,(int)($_POST['points_used']??0)); $err='';
  $as=$pdo->prepare('SELECT * FROM addresses WHERE id=? AND user_id=?');$as->execute([$address,user_id()]);$addr=$as->fetch(); if(!$addr)$err='Please select a delivery address.';
  $valid=[];$subtotal=0;
  if(!$err){$pdo->beginTransaction();try{foreach($items as $i){$vid=(int)($i['variant_id']??0);$qty=(float)($i['qty']??0);if($vid<1||$qty<=0)continue;$s=$pdo->prepare('SELECT v.*,p.id product_id,p.name FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.id=? AND p.is_active=1 FOR UPDATE');$s->execute([$vid]);$v=$s->fetch();if(!$v||$qty>(float)$v['stock'])throw new RuntimeException('One or more products are out of stock.');$valid[]=['v'=>$v,'qty'=>$qty];$subtotal+=$qty*(float)$v['price'];}if(!$valid)throw new RuntimeException('Your cart is empty.');
    $discount=0;if($coupon){$cs=$pdo->prepare('SELECT * FROM coupons WHERE code=? AND is_active=1 AND (start_at IS NULL OR start_at<=NOW()) AND (end_at IS NULL OR end_at>=NOW()) AND (usage_limit IS NULL OR used_count<usage_limit)');$cs->execute([$coupon]);$c=$cs->fetch();if(!$c||$subtotal<(float)$c['min_order'])throw new RuntimeException('Invalid or inapplicable coupon.');$discount=$c['type']==='percent'?min($subtotal*(float)$c['value']/100,(float)($c['max_discount']??PHP_INT_MAX)):(float)$c['value'];$discount=min($discount,$subtotal);}
    $pointDiscount=0;$balance=(int)$pdo->query('SELECT points FROM users WHERE id='.(int)user_id())->fetchColumn();if($pointsUsed){if(!setting_bool($pdo,'points_enabled')||!setting_bool($pdo,'redeem_enabled')||$pointsUsed<((int)setting($pdo,'redeem_min_points','100'))||$pointsUsed>$balance)throw new RuntimeException('Invalid points redemption.');$pointDiscount=min($pointsUsed*(float)setting($pdo,'point_value_rupees','1'),max(0,$subtotal-$discount));$discount+=$pointDiscount;}
    $handling=(float)setting($pdo,'handling_charge','15');$delivery=max(0,$subtotal-$discount)>499?0:40;$total=max(0,$subtotal-$discount)+$handling+$delivery;$orderNo='AG'.date('ymdHis').random_int(10,99);$earn=setting_bool($pdo,'points_enabled')?(int)floor($subtotal/100*(float)setting($pdo,'points_per_100','1')):0;
    $os=$pdo->prepare('INSERT INTO orders(order_no,user_id,address_id,subtotal,handling_charge,delivery_fee,discount,points_used,points_earned,coupon_code,total,payment_method,payment_status,status,delivery_slot) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$os->execute([$orderNo,user_id(),$address,$subtotal,$handling,$delivery,$discount,$pointsUsed,$earn,$coupon?:null,$total,$payment,'pending','placed',trim($_POST['delivery_slot']??'Any available slot')]);$oid=(int)$pdo->lastInsertId();$is=$pdo->prepare('INSERT INTO order_items(order_id,product_id,variant_id,product_name,variant_label,qty,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?)');$ss=$pdo->prepare('UPDATE product_variants SET stock=stock-? WHERE id=? AND stock>=?');foreach($valid as $x){$v=$x['v'];$q=$x['qty'];$ss->execute([$q,$v['id'],$q]);if($ss->rowCount()!==1)throw new RuntimeException('Inventory changed. Please retry.');$is->execute([$oid,$v['product_id'],$v['id'],$v['name'],$v['label'],$q,$v['price'],$q*$v['price']]);}$pdo->prepare('UPDATE coupons SET used_count=used_count+1 WHERE code=? AND ?<>""')->execute([$coupon,$coupon]);if($pointsUsed){$pdo->prepare('UPDATE users SET points=points-? WHERE id=?')->execute([$pointsUsed,user_id()]);$pdo->prepare('INSERT INTO point_transactions(user_id,points,reason,order_id) VALUES(?,?,?,?)')->execute([user_id(),-$pointsUsed,'Points redeemed',$oid]);}if($earn){$pdo->prepare('UPDATE users SET points=points+? WHERE id=?')->execute([$earn,user_id()]);$pdo->prepare('INSERT INTO point_transactions(user_id,points,reason,order_id) VALUES(?,?,?,?)')->execute([user_id(),$earn,'Order points',$oid]);}$pdo->commit();
    echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="3;url='.e(url('account/')).'"><title>Order placed</title><link rel="stylesheet" href="'.e(url('assets/css/style.css')).'"></head><body><main class="container page"><div class="panel success-order"><div class="success-icon">✓</div><span class="eyebrow">ORDER CONFIRMED</span><h1>Thank you for your order!</h1><p>Your order <strong>'.e($orderNo).'</strong> has been created.</p><p class="hint">Returning to your account…</p><a class="btn btn-primary" href="'.e(url('account/')).'">View My Account</a></div></main></body></html>';exit;
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$err=$e->getMessage();}}
}
$title='Cart & Checkout | '.APP_NAME;include __DIR__.'/includes/header.php';
$addresses=[];$userPoints=0;if(is_logged_in()){$st=$pdo->prepare('SELECT * FROM addresses WHERE user_id=? ORDER BY is_default DESC,id DESC');$st->execute([user_id()]);$addresses=$st->fetchAll();$userPoints=(int)$pdo->query('SELECT points FROM users WHERE id='.(int)user_id())->fetchColumn();}
?>
<section class="container page"><div class="section-head"><div><span class="eyebrow">YOUR BASKET</span><h1>Cart & checkout</h1><p class="hint">Review your basket, choose delivery and go directly to payment.</p></div><a class="btn" href="<?=url()?>">Continue shopping</a></div>
<?php if($err): ?><div class="alert"><?=e($err)?></div><?php endif; ?>
<div id="cart-root" class="cart-checkout-layout"><div class="cart-main"><div class="panel"><div id="cartItems"><p class="hint">Loading your basket…</p></div></div>
<?php if(is_logged_in()): ?><form method="post" id="orderForm" class="panel checkout-panel"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="cart_json" id="cartJson"><h2>Delivery details</h2><?php if($addresses): ?><div class="address-options"><?php foreach($addresses as $a): ?><label class="address-choice"><input type="radio" name="address_id" value="<?=$a['id']?>" <?=$a['is_default']?'checked':''?>><span><b><?=e($a['address_type']??$a['label'])?></b> <?=($a['is_default']?'<small class="default-badge">Default</small>':'')?><br><?=e($a['apartment_no'])?> <?=e($a['apartment_name'])?>, <?=e($a['area'])?><br><?=e($a['address_line'])?>, <?=e($a['city'])?> - <?=e($a['pincode'])?></span></label><?php endforeach; ?></div><?php else: ?><div class="empty-mini">No delivery address saved. <a href="<?=url('account/#addresses')?>">Add an address</a></div><?php endif; ?><a class="btn" href="<?=url('account/#addresses')?>">+ Add / manage address</a>
<div class="field-grid compact"><label>Delivery slot<select name="delivery_slot"><option>Any available slot</option><option>7 AM - 10 AM</option><option>10 AM - 1 PM</option><option>5 PM - 8 PM</option><option>8 PM - 10 PM</option></select></label><label>Payment method<div class="payment-options"><label><input type="radio" name="payment_method" value="cod" checked> COD</label><label><input type="radio" name="payment_method" value="razorpay"> UPI / Online</label></div></label></div>
<div class="coupon-points"><div><label>Coupon code<div class="input-action"><input name="coupon" placeholder="Enter coupon"><button type="button" class="btn" id="applyCoupon">Apply</button></div></label></div><div><label>Points to redeem (<?=number_format($userPoints)?> available)<input name="points_used" type="number" min="0" step="1" value="0"></label></div></div>
<button class="btn btn-primary pay-btn" id="payBtn">Go to payment →</button></form><?php else: ?><div class="panel login-checkout"><h2>Login to checkout</h2><p class="hint">Sign in to select a delivery address and continue to payment.</p><a class="btn btn-primary" href="<?=url('login.php?return=cart/') ?>">Continue with Gmail / Login</a></div><?php endif; ?></div>
<aside class="panel cart-summary"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><b id="cartSubtotal">₹0.00</b></div><div class="summary-row"><span>Handling charge <button type="button" class="info-tip" id="handlingInfo" aria-label="Handling charge information">i</button></span><b id="cartHandling">₹0.00</b></div><div id="handlingTip" class="tooltip-box" role="tooltip">A small handling charge helps cover packing, sorting and order processing.</div><div class="summary-row"><span>Delivery</span><b id="cartDelivery">₹0.00</b></div><div class="summary-row total"><span>Total</span><b id="cartTotal">₹0.00</b></div><p class="hint">Taxes and final payment amount are confirmed before payment.</p></aside></div></section>
<script>document.getElementById('orderForm')?.addEventListener('submit',e=>{document.getElementById('cartJson').value=localStorage.getItem('aapki_cart_v2')||'[]';const c=JSON.parse(document.getElementById('cartJson').value||'[]');if(!c.length){e.preventDefault();alert('Your cart is empty.');}});document.getElementById('handlingInfo')?.addEventListener('click',()=>document.getElementById('handlingTip').classList.toggle('show'));document.getElementById('applyCoupon')?.addEventListener('click',()=>{document.getElementById('orderForm').requestSubmit();});</script>
<?php include __DIR__.'/includes/footer.php'; ?>
