<?php
require_once __DIR__.'/../config/db.php';$pdo=db();
if(!GOOGLE_CLIENT_ID||!GOOGLE_CLIENT_SECRET){flash('error','Google/Gmail login needs GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in config.php.');redirect('login.php');}
$redirectUri=url('auth/google.php?callback=1');
// Only allow safe, local, relative return paths (prevents open-redirect).
function safe_return(string $r):string{$r=trim($r);if($r===''||preg_match('~^(https?:)?//~i',$r)||str_starts_with($r,'/')||str_contains($r,'..'))return '';return $r;}
if(empty($_GET['callback'])){$state=bin2hex(random_bytes(24));$_SESSION['oauth_state']=$state;$_SESSION['oauth_return']=safe_return($_GET['return']??'');$params=http_build_query(['client_id'=>GOOGLE_CLIENT_ID,'redirect_uri'=>$redirectUri,'response_type'=>'code','scope'=>'openid email profile','state'=>$state,'access_type'=>'online','prompt'=>'select_account']);redirect('https://accounts.google.com/o/oauth2/v2/auth?'.$params);}
if(!hash_equals($_SESSION['oauth_state']??'',$_GET['state']??'')){flash('error','OAuth state validation failed.');redirect('login.php');}
$ch=curl_init('https://oauth2.googleapis.com/token');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_POSTFIELDS=>http_build_query(['code'=>$_GET['code']??'','client_id'=>GOOGLE_CLIENT_ID,'client_secret'=>GOOGLE_CLIENT_SECRET,'redirect_uri'=>$redirectUri,'grant_type'=>'authorization_code'])]);$token=json_decode(curl_exec($ch),true);curl_close($ch);if(empty($token['access_token'])){flash('error','Google login could not be completed.');redirect('login.php');}
$ch=curl_init('https://openidconnect.googleapis.com/v1/userinfo');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token['access_token']]]);$info=json_decode(curl_exec($ch),true);curl_close($ch);if(empty($info['email'])){flash('error','Google did not return an email address.');redirect('login.php');}
$picture=$info['picture']??null;
$s=$pdo->prepare("SELECT * FROM users WHERE provider='google' AND provider_id=? LIMIT 1");$s->execute([$info['sub']]);$u=$s->fetch();if(!$u){$s=$pdo->prepare('SELECT * FROM users WHERE email=? LIMIT 1');$s->execute([$info['email']]);$u=$s->fetch();if($u){$st=$pdo->prepare("UPDATE users SET provider='google',provider_id=?,name=?,avatar=COALESCE(?,avatar) WHERE id=?");$st->execute([$info['sub'],$info['name']??$u['name'],$picture,$u['id']]);}else{$code='AG'.strtoupper(bin2hex(random_bytes(4)));$st=$pdo->prepare("INSERT INTO users(name,email,avatar,provider,provider_id,role_slug,referral_code) VALUES(?,?,?,?,?, 'customer',?)");$st->execute([$info['name']??'Customer',$info['email'],$picture,$info['sub'],$code]);$u=['id'=>$pdo->lastInsertId(),'role_slug'=>'customer'];}}else{if($picture){$pdo->prepare('UPDATE users SET avatar=? WHERE id=?')->execute([$picture,$u['id']]);}}
session_regenerate_id(true);$_SESSION['user_id']=(int)$u['id'];$_SESSION['role']=$u['role_slug'];$raw=bin2hex(random_bytes(32));$st=$pdo->prepare('UPDATE users SET remember_token_hash=? WHERE id=?');$st->execute([hash('sha256',$raw),(int)$u['id']]);setcookie('aapki_remember',$raw,['expires'=>time()+31536000,'path'=>BASE_URL,'secure'=>!empty($_SERVER['HTTPS']),'httponly'=>true,'samesite'=>'Lax']);
$ret=safe_return($_SESSION['oauth_return']??'');unset($_SESSION['oauth_return']);
if(($u['role_slug']??'customer')!=='customer'){redirect('admin/');}
redirect($ret!==''?$ret:'account/');
