<?php require_once __DIR__.'/../config/db.php';$pdo=db();$slug=trim($_GET['slug']??'');$cat=trim($_GET['cat']??'');
if($cat){$s=$pdo->prepare('SELECT p.*,c.name category_name,c.slug category_slug FROM products p JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND c.slug=? AND p.is_active=1');$s->execute([$slug,$cat]);}else{$s=$pdo->prepare('SELECT p.*,c.name category_name,c.slug category_slug FROM products p JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.is_active=1');$s->execute([$slug]);}$p=$s->fetch();
if(!$p){http_response_code(404);$title='Product not found | '.APP_NAME;include __DIR__.'/../includes/header.php';echo '<section class="container page"><div class="empty"><h2>Product not found</h2><a class="btn" href="'.e(url()).'">Back to shopping</a></div></section>';include __DIR__.'/../includes/footer.php';exit;}
$title=$p['meta_title']?:$p['name'].' | '.APP_NAME;$description=$p['meta_description']?:($p['description']?:'Buy '.$p['name'].' online at Aapki Grocery.');$keywords=$p['meta_keywords']?:$p['name'].', '.$p['category_name'].', Aapki Grocery';$ogImage=product_image($p);$vs=$pdo->prepare('SELECT * FROM product_variants WHERE product_id=? ORDER BY is_default DESC,id');$vs->execute([$p['id']]);$variants=$vs->fetchAll();$default=$variants[0]??['id'=>0,'price'=>$p['price'],'mrp'=>$p['mrp'],'stock'=>$p['stock'],'label'=>'1 Unit'];
$related=$pdo->prepare('SELECT p.*,c.name category_name FROM products p JOIN categories c ON c.id=p.category_id WHERE p.category_id=? AND p.id<>? AND p.is_active=1 ORDER BY p.is_featured DESC,p.id DESC LIMIT 8');$related->execute([$p['category_id'],$p['id']]);$related=$related->fetchAll();include __DIR__.'/../includes/header.php';
?>
<section class="container product-detail"><div class="detail-image"><img src="<?=e(product_image($p))?>" alt="<?=e($p['name'])?>" fetchpriority="high" onerror="this.onerror=null;this.src='<?=e(url('assets/images/products/product-placeholder.svg'))?>';"></div><div class="detail-info"><div class="breadcrumbs"><a href="<?=url($p['category_slug'].'/#products')?>"><?=e($p['category_name'])?></a> <span>›</span> <?=e($p['name'])?></div><span class="eyebrow"><?=e($p['category_name'])?></span><h1><?=e($p['name'])?></h1><p><?=nl2br(e($p['description']))?></p><label class="select-label">Choose quantity</label><div class="variant-pills"><?php foreach($variants as $i=>$v): ?><button type="button" class="variant-pill <?=$i===0?'active':''?>" data-id="<?=$v['id']?>" data-price="<?=$v['price']?>" data-mrp="<?=$v['mrp']?>" data-stock="<?=$v['stock']?>"><?=e($v['label'])?></button><?php endforeach; ?></div><div class="price-row detail-price"><strong id="detailPrice">₹<?=number_format((float)$default['price'],2)?></strong><del id="detailMrp"><?=($default['mrp']>$default['price'])?'₹'.number_format((float)$default['mrp'],2):''?></del></div><button id="detailAdd" class="btn add-btn" type="button" data-variant="<?=e((string)$default['id'])?>">Add to Cart</button><p class="stock-note" id="stockNote"></p></div></section>
<section class="container products-section related-products"><div class="section-head"><div><span class="eyebrow">FROM THE SAME CATEGORY</span><h2>More <?=e($p['category_name'])?></h2></div><a class="btn" href="<?=url($p['category_slug'].'/#products')?>">View all</a></div><div class="product-grid"><?php $products=$related;include __DIR__.'/../includes/product_cards.php'; ?></div></section>
<script>const detailButtons=document.querySelectorAll('.variant-pill'),add=document.getElementById('detailAdd'),stockNote=document.getElementById('stockNote');function detailState(){const a=document.querySelector('.variant-pill.active');if(!a)return;add.dataset.variant=a.dataset.id;const stock=Number(a.dataset.stock||0);add.disabled=stock<=0;add.textContent=stock>0?'Add to Cart':'Coming Soon';stockNote.textContent=stock>0?stock+' available':'Currently unavailable';}detailButtons.forEach(b=>b.addEventListener('click',()=>{detailButtons.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('detailPrice').textContent='₹'+Number(b.dataset.price).toFixed(2);document.getElementById('detailMrp').textContent=Number(b.dataset.mrp)>Number(b.dataset.price)?'₹'+Number(b.dataset.mrp).toFixed(2):'';detailState()}));add?.addEventListener('click',()=>{if(add.disabled)return;const id=Number(add.dataset.variant);let c=[];try{c=JSON.parse(localStorage.getItem('aapki_cart_v2')||'[]')}catch(e){}const x=c.find(v=>v.variant_id===id);if(x)x.qty++;else c.push({variant_id:id,qty:1});localStorage.setItem('aapki_cart_v2',JSON.stringify(c));document.querySelectorAll('#cartCount').forEach(x=>x.textContent='('+c.reduce((a,v)=>a+v.qty,0)+')');add.textContent='Added ✓';setTimeout(detailState,900)});detailState();</script><?php include __DIR__.'/../includes/footer.php';?>
