<?php
/**
 * Seed content for the `pages` table — supplied Aapki Grocery copy.
 * Returned as an array; the migration inserts these once.
 */

$aboutBody = <<<'HTML'
<p>aapkigrocery is an online food specialist offering an extensive range of premium products with unbeatable value so that you can always feel good about what you eat. We are here to elevate your grocery shopping experience.</p>
<p>Our sourcing of fresh fruits, vegetables, juices &amp; dairy is straight from the farms, manufacturer and famous brands direct to your door.</p>
<p>We believe in curating and selling some of the finest and most innovative products at value and aim to use completely sustainable packaging and be completely carbon neutral.</p>
<p>Our network is deep rooted with farmers following hygienic and sustainable farming practices.</p>
<h2>Freshest Produce</h2>
<p>If you are not happy with the quality of fresh fruits and vegetables currently available with leading retailers both online and offline – you are not alone. These days, while customers are inundated with fake discounts and spurious offers and there is an insane rush for lowest prices, quality often remains questionable in fresh products especially. We have stepped in to bridge this “quality” gap. aapkigrocery is born with the exclusive purpose of serving quality to its customers.</p>
<h2>Carefully Curated Selection</h2>
<p>More than 400 fresh food items out of which more than 250 active SKUs of fruits and vegetables in all seasons – largest range in market. We also offer a select range of groceries which we are expanding based on customer feedback.</p>
<h2>Direct to Customer</h2>
<p>We handle all our fresh products &amp; ensuring proper hygiene. Packaging is 100% recyclable and 100% foodgrade, contact surfaces where product are all non-porous material (steel) and clean.</p>
<h2>Traceability</h2>
<p>If you were to visit the packing and warehousing facilities of some big names – you will be shocked with conditions in which the fresh produce is handled. We handle all our fresh products proper hygiene. Packaging is 100% recyclable and 100% foodgrade, contact surfaces where product are all non-porous material (steel) and clean.</p>
HTML;

$termsBody = <<<'HTML'
<h2>Introduction</h2>
<p>aapkigrocery Private Limited (the “Website Owner”) operates the website www.aapkigrocery.com (the “Website”). The Website Owner, including affiliates (or "we" or "us" or "our" or “aapkigrocery”) provides the information contained on this Website or any of the pages comprising the Website to visitors ("Visitors") (cumulatively referred to as "you" or "your" hereinafter) subject to the terms and conditions set out in these Website terms and conditions, the privacy policy and any other relevant terms and conditions, policies and notices which may be applicable to a specific section or module of this website. Please read this agreement carefully. By browsing, accessing or using this website or by using any facilities or services made available through it or by transacting through or on it, you are agreeing to the terms and conditions that appear below (all of which are called the "Agreement"). This Agreement is made between you and us.</p>
<h2>Website Availability</h2>
<p>aapkigrocery may suspend the Website for any reason whatsoever, including but not limited to repairs, planned maintenance or upgrades, and shall not be liable to you for any such suspension.</p>
<p>aapkigrocery reserves the right to make any changes to the Website or to discontinue any aspect or feature of the Website without notice.</p>
<p>In the event that aapkigrocery, in its sole discretion, considers that you are making any illegal and/or unauthorised use of the Website, and/or your use of the Website is in breach of these Terms, aapkigrocery reserves the right to take any action that it deems necessary, including terminating without notice your use of the Website and, in the case of illegal use, initiating legal proceedings.</p>
<h2>Your Status</h2>
<p>By placing an order to purchase Products (Order) through the Website, you warrant that:</p>
<ul><li>You are legally capable of entering into binding contracts; and</li><li>You are at least 18 years old.</li></ul>
<h3>The Contract Between You And aapkigrocery</h3>
<p>After placing an Order, you will receive an email from aapkigrocery acknowledging that aapkigrocery has received your order. Please note that this does not mean that your Order has been accepted. All orders are subject to availability of the items that are ordered, and aapkigrocery will confirm such acceptance to you by sending you an email that confirms that the Product has been dispatched (out for delivery confirmation). The contract between aapkigrocery and you (Contract) will only be formed when aapkigrocery sends you the dispatch confirmation.</p>
<p>Each Contract relates only to those Products whose dispatch aapkigrocery has confirmed in the dispatch confirmation. aapkigrocery shall not be obliged to supply any other Products which may have been part of your Order until the dispatch of such Products has been confirmed by way of a dispatch confirmation.</p>
<p>For the avoidance of doubt, your contract with aapkigrocery relates only to your use of the Website and the services available therein.</p>
<h2>Credit Card or Debit Card Payments</h2>
<p>We have built in relevant security systems on the website based on the prevalent industry standards. Our payment systems are managed by third party payment gateways (CCAvenues), which are a reputed and renowned manager of payment gateways with the relevant security checks built-in. Payments are made only after a multiple level check including encryption and passwords. In a card transaction, you must use your own credit card or debit card or other payment cards. We will not be liable for any payment fraud due to use of your card by any other person, whether known or unknown to you. The liability for use of a card fraudulently will be on the user and the onus to 'prove otherwise' shall be exclusively on the user.</p>
<h2>Trademarks</h2>
<p>The trademarks, names, logos and service marks (collectively "trademarks") displayed on this website are registered and unregistered trademarks of the Website Owner and the suppliers of the products listed on the Website. Nothing contained on this website should be construed as granting any licence or right to use any trademark without the prior written permission of the Website Owner.</p>
<h2>External Links</h2>
<p>External links may be provided for your convenience, but they are beyond the control of the Website Owner and no representation is made as to their content. Use or reliance on any external links and the content thereon provided is at your own risk. When visiting external links you must refer to that external websites terms and conditions of use. No hypertext links shall be created from any website controlled by you or otherwise to this website without the express prior written permission of the Website Owner. Please contact us at admin@aapkigrocery.com if you would like to link to this website or would like to request a link to your website.</p>
<h2>Specific Use</h2>
<p>You further agree not to use the website to send or post any message or material that is unlawful, harassing, defamatory, abusive, indecent, threatening, harmful, vulgar, obscene, sexually orientated, racially offensive, profane, pornographic or violates any applicable law and you hereby INDEMNIFY the Website Owner against any loss, liability, damage or expense of whatever nature which the Website Owner or any third party may suffer which is caused by or attributable to, whether directly or indirectly, your use of the website.</p>
<h2>Delivery</h2>
<p><b>Both parties agree and confirm that:</b></p>
<p>i) in the event that a non-delivery occurs on account of a mistake by you (i.e. wrong name or address or phone number or any other wrong information) aapkigrocery shall not be obligated to attempt re-delivery. However, if in good faith/upon request from you, we do attempt redelivery, you agree and undertake to bear the additional costs incurred by us for the proposed redelivery – including the cost of delivery and the value of items which are spoiled due to perishable or delicate nature of product being delivered and multiple handlings. Further, if a re-delivery means any extra costs are incurred by us, in addition to the amount you have already paid, you warrant to make such additional payment promptly upon request made by us.</p>
<p>ii) in the event that a non-delivery or delayed delivery occurs on account of a force majeure event, riots, terrorism, sabotage, epidemic, quarantine restrictions, accident, fire, flood, tempest, earthquake, civil commotion, traffic jams, heavy rains or storm, barricading, curfew, traffic restrictions, transport strike, governmental action or other causes, which are beyond the control of one party, other party shall not be entitled to any claim for damages against the other in respect of such non-delivery or delay in delivery.</p>
<p>iii) in the event that a partial or full, non-delivery or delayed delivery occurs on account of a decision or mistake on our part, to that extent of missed or delayed delivery, you shall not be obligated to pay (for non-delivery) and not obligated to accept the delivery (for delayed delivery). If you have already made payment for a delivery which is missed due to an act on our part, and you choose not to receive a re-delivery or a delayed delivery or an equivalent credit to your e-wallet, we shall refund that amount to the source of payment within 07 working days.</p>
<h2>aapkigrocery Returns Policy</h2>
<p>It is our sincere endeavor to serve you with good quality products. If you happen to receive a defective product at the time of delivery, you can refuse the products at the time of delivery and get refund to the e-wallet or refund to the source, at your option. If you notice a defect or deficiency in a product after delivery has been accepted by you, you can raise a return or replacement request by sending an email to admin@aapkigrocery.com or by clicking on the “complaints/suggestions” button in the “my orders” page in “my account” section of our website, within the timelines specifically defined in our Cancellations and Returns policy. The request received after the applicable periods will not be entertained. For returns initiated within the allowed period, we will refund the amount to e-wallet or to the original payment source within 07 (seven) working days.</p>
<h2>Limitation of Liability</h2>
<p>The aggregate liability of the website owners and its directors, officers, employees, agents, sub-contractors, to the user of the website in respect of any claims, losses, costs or damages arising out of the sale of products or services on the website shall not exceed the total amount of payment received from a user. In the event of our product or services being found defective we are liable to make good any actual and direct loss for the amount paid by you to us and under no circumstance shall we be liable for any indirect, consequential, special or exemplary damages or losses. No liability shall be admissible towards the claims arising out of any alleged bodily injury, disease, sickness or indisposition of any individuals as a result of the possession or consumption or use of any product sold through our website.</p>
<h2>Product Recall</h2>
<p>If the website owners, in good faith decide to recall a product due to an actual product defect, a perceived product defect, intended product improvements, in response to consumer complaints or any other reasons whatsoever, then the buyer of those products shall be intimated via email or message or phone call. It shall be at full discretion of the purchaser whether he or she chooses to respond to a product recall notice and whether to return the product or not. If the purchaser chooses to return the product he or she shall receive full refund or credit to their e-wallet or replacement for the amount spent including the purchase, delivery, pick-up or any associated charges. If the customer chooses not to respond to the recall notice or is unable to respond to recall by virtue of having already used the product, then such user shall not be eligible for any refunds. Irrespective of whether the user chooses to return the product(s) in question or not, the Company’s overall liability shall remain limited by the total amount actually paid by the customer as described in clause “Limitation of Liability” hereinabove.</p>
<h2>Best Before Date for Fresh products</h2>
<p>The primary purpose of the website is to sell to our consumers good quality food products including fresh (fresh fruits, vegetables, dairy, meat and related products), near-fresh food products (example cut or washed vegetables, cold pressed juices etc.) and other food products. As the user might be aware, fresh food products are subject to perishability within a relatively short shelf life. There are guidelines regarding their consumption prior to a mentioned “best before date” and the applicable storage conditions. Owing to the fact that the fresh products are natural products, which are subject to natural processes and phenomena, which are not comprehensively enlisted, not completely understood and not fully controllable, fresh products may change some of their characteristics like colour, taste, texture or freshness and may become unfit for consumption even prior to the suggested best before date. On the other hand, a product past its “best before date” mentioned on the packaging, may lose some or all of its freshness, taste, aroma or nutrients. It may be unfit or unsafe to eat but not necessarily so. We have not conducted any research &amp; development to arrive at a scientifically accurate “best before date” for the fresh products. The “best before date” mentioned on our fresh product packages has been mentioned, in good faith, to help you decide the duration during which the product remains consumable, based on our best estimates of shelf life duration after which a product might not remain fit for consumption, if and only if, the advised storage conditions (temperature, moisture etc) have been strictly followed. However, you should consume a fresh product, even before its “best before date”, relying on your own senses (smell, sight, taste, touch etc.) and not indiscriminately relying on the mentioned “best before date” on the package. You should consume a fresh product being fully aware that the ultimate responsibility to decide whether to consume or when to consume a fresh product lies with yourself. This advice is not meant to absolve us of our commitment to deliver good quality products to you and if you find that a product has been delivered to you in a defective or deteriorated state, we commit to either refund the amount paid or give you an equivalent credit in your e-wallet, at your choice. Any such issue has to be highlighted at the time of delivery or immediately after the delivery more fully described in our Cancellations and Returns Policy.</p>
<h2>Claimed or Actual Health Benefits of Products</h2>
<p>The products marketed and sold on the website may mention certain health benefits by the respective manufacturers, suppliers, importers or distributors of those products. Further, certain natural products have perceived health benefits which are prevalent common beliefs (Example: Amla/Indian gooseberry boosts immunity) supported by various media, web forums, blogs and publications. Any such claims have not been independently verified by us and we don’t undertake any responsibility for the accuracy or truth of such claims. User of the website should do their own independent research to reach at the conclusion of health benefits of any product whether natural or processed.</p>
<h2>Perceived or Actual health risks of the products</h2>
<p>The products marketed and sold on the website may pose health risks for individual based on their gender, age groups, health conditions, category (ex: pregnant women) or individuals suffering from certain allergies or diseases. Such individuals have to do their own research and consult their own sources of advice whether to consume any one or more products listed on the website. No specific health warnings have been mentioned against the individual products for any unsuitability or risks associated with their consumption. Any such risks have neither been researched by us nor published on the website. User of the website should do their own independent research to reach at the conclusion of health benefits of any product whether natural or processed. For example: if Mango is unfit for diabetic patient of a certain type and age – it will NOT be mentioned against the product “mango” being sold on website and the individuals buying the Mango are expected to know the risks and suitability of its consumption.</p>
<h2>No Commercial Use</h2>
<p>This Website is for your personal, non-commercial use only. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, commercially exploit, create derivative works from, transfer, or sell any content, software, products, or services contained within this site. You may not use this site, or any of its content, to further any commercial purpose, including any advertising or advertising revenue generation activity on your own site.</p>
<h2>Visitor Registration</h2>
<p>Visitors will need to register with the Website in order to use some of the services or features made available on this Website. When you register, you are required to provide information about yourself that is current and complete for the purpose for which it is sought (example: your delivery address and your phone numbers). Should any of your registration information change, please notify us immediately either using the Website’s automated service, or via e-mail at admin@aapkigrocery.com. We may change registration requirements from time to time.</p>
<h2>General</h2>
<h3>Entire Agreement</h3>
<p>These website terms and conditions along with the i) Privacy policy and ii) Cancellation and returns policy constitute the sole record of the agreement between you and the Website Owner in relation to your use of the website. Neither you nor the Website Owner shall be bound by any express, tacit or implied representation, warranty, promise or the like not recorded herein. Unless otherwise specifically stated these website terms and conditions supersede and replace all prior commitments, undertakings or representations, whether written or oral, between you and the Website Owner in respect of your use of the website.</p>
<h3>Alteration</h3>
<p>The Website Owner may at any time modify any relevant terms and conditions, policies or notices. You acknowledge that by visiting the website from time to time, you shall become bound to the current version of the relevant terms and conditions (the "current version") and, unless stated in the current version, all previous versions shall be superseded by the current version. You shall be responsible for reviewing the then current version each time you visit the website.</p>
<h3>Conflict</h3>
<p>Where any conflict or contradiction appears between the provisions of these website terms and conditions and any other relevant terms and conditions, policies or notices, the other relevant terms and conditions, policies or notices which relate specifically to a particular section or module of the website shall prevail in respect of your use of the relevant section or module of the website.</p>
<h3>Waiver</h3>
<p>No indulgence or extension of time which either party may grant to the other will constitute a waiver of or, whether by estoppel or otherwise, limit any of the existing or future rights of the grantor in terms hereof, save in the event or to the extent that the grantor has signed a written document expressly waiving or limiting such rights.</p>
<h3>Cession</h3>
<p>The Website Owner shall be entitled to cede, assign and delegate all or any of its rights and obligations in terms of any relevant terms and conditions, at its own discretion.</p>
<h3>Severability</h3>
<p>All provisions of any relevant terms and conditions, policies and notices are, notwithstanding the manner in which they have been grouped together or linked grammatically, severable from each other. Any provision of any relevant terms and conditions, policies and notices, which is or becomes unenforceable in any jurisdiction, whether due to voidness, invalidity, illegality, unlawfulness or for any reason whatever, shall, in such jurisdiction only and only to the extent that it is so unenforceable, be treated as pro non scripto and the remaining provisions of any relevant terms and conditions, policies and notices shall remain in full force and effect.</p>
<h3>Applicable Jurisdiction</h3>
<p>Any relevant terms and conditions, policies and notices shall be governed by and construed in accordance with the laws of India without giving effect to any principles of conflict of law. You hereby consent to the exclusive jurisdiction of the courts of Delhi, India in respect of any disputes arising in connection with the website, or any relevant terms and conditions, policies and notices or any matter related to or in connection therewith.</p>
<h3>Comments or Questions</h3>
<p>If you have any questions, comments or concerns arising from the website or any other relevant terms and conditions, policies and notices, please contact us.</p>
<p>Email id: askme@aapkigrocery.com</p>
HTML;

$privacyBody = <<<'HTML'
<h2>Consent to Privacy Policy</h2>
<p>We respect and protect your right to privacy as set forth in this Privacy Policy. This Privacy Policy provides the manner in which your data is collected and used/shared by aapkigrocery. As a visitor to the website/ Customer you are advised to read the Privacy Policy carefully.</p>
<p>Note:</p>
<p>i) By visiting this website you agree to be bound by the terms and conditions of this Privacy Policy. If you do not agree, please do not use or access our Website.</p>
<p>ii) By mere use of the website, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms &amp; Conditions.</p>
<p>iii) Our Website may have links to other websites that may collect personally identifiable information about you. FIPL is not responsible for the privacy practices or the content of those linked websites.</p>
<h2>What information is, or may be, collected from you?</h2>
<p>The information we learn from customers helps us personalise and improve your shopping experience at aapkigrocery.com. We use your information in handling orders, delivering products and services, processing payments, communicating with you about orders, products, services and promotional offers, updating our records and generally maintaining your accounts with us, displaying content such as suggested products and customer reviews and recommending merchandise and services that might be of interest to you. We also use this information to improve our platform, prevent or detect fraud or abuses of our website and enable third parties to carry out technical, logistical or other functions on our behalf.</p>
<p>Here are the types of information we gather.</p>
<p><b>Information provided by you:</b> We may receive and may store any information you enter on our website or give us in any other way. We use the information that you provide for such purposes as responding to your requests, customising future shopping for you, improving our website, and communicating with you.</p>
<p><b>Automatic Information:</b> We receive and store certain types of information whenever you interact with the website. For example, we use "cookies" and we might obtain certain types of information when your Web browser accesses the site or advertisements and other content served by or on behalf of the site on other websites. We may also receive/store information about your location and your mobile device. With your consent, we may have access to your SMS, contacts in your directory, call history, location and device information.</p>
<p><b>E-mail communications:</b> To help us make e-mails more useful and interesting, we may receive a confirmation when you open e-mail from us if your computer supports such capabilities. We may also compare our customer list to information received from other sources in an effort to avoid sending unnecessary messages to our customers. If you do not want to receive e-mail or other mail from us, please adjust your subscription preferences in my account.</p>
<p><b>Information from Other Sources:</b> We might receive information about you from other online and offline sources and add it to your account information.</p>
<h2>Use of information</h2>
<p>We use personal information to provide the services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We may use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect money; measure consumer interest in our products and services, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection.</p>
<p>We may use location based information from your device for internal analysis and to provide you with location-based services, such as advertising, search results, and other personalized content. We identify and use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify your location and to gather broad demographic information.</p>
<p>In our efforts to continually improve our product and service offerings, we collect and analyse demographic and profile data about our users' activity on our Website. We may occasionally ask you to complete optional online surveys. These surveys may ask you for contact information and demographic information (like zip code, age, or income level). We use this data to tailor your experience at our Website, providing you with content that we think you might be interested in and to display content according to your preferences.</p>
<h2>Sharing of information</h2>
<p>We may share personal information with our affiliates. If allowed by you in your subscription preferences, these affiliates may market to you as a result of such sharing.</p>
<p>We may disclose your personal information to third parties. This disclosure may be required for us to provide you access to our services (example: delivery services), to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.</p>
<p>We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our terms or Privacy Policy; respond to claims that a content on our website violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>
<p>We and our affiliates may share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur, the other business entity (or the new combined entity) might not follow this privacy policy, in which circumstance the updated policy shall be shared on the website of such new entity.</p>
<h2>What Choices are available to you regarding collection, use and distribution of your information?</h2>
<p>You can choose not to provide certain information but then you might not be able to use our website.</p>
<p>Most browsers can be set to prevent cookies or to notify you when one is being placed, whereby you may choose not to let the cookies be placed in your systems, however in that event you may not be able to access our website.</p>
<p>You may change your email settings to avoid letting us know if you access an email sent by us. Further, we provide all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us, after setting up an account. If you want to remove your contact information from all non-essential (not needed for servicing your orders or your account) aapkigrocery.com lists, please visit the unsubscribe page in my accounts section on the website.</p>
<h2>Advertisements on aapkigrocery.com</h2>
<p>We may use third-party advertising companies to serve ads when you visit our Website. These companies may use information about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.</p>
<h2>No Liability</h2>
<p>To protect against the loss, misuse and alteration of the information under its control, FIPL has in place appropriate physical, electronic and managerial procedures. For example, FIPL servers are accessible only to authorized personnel and your information is shared with employees and authorised personnel on a need to know basis to complete the transaction and to provide the services requested by you. Although FIPL will endeavour to safeguard the confidentiality of your personally identifiable information, it is not guaranteed that the transmissions made by means of the Internet are completely secure. By using this website, you agree that FIPL will have no liability for inadvertent disclosure of your information due to errors in transmission or unauthorized acts of third parties.</p>
<h2>Policy updates</h2>
<p>FIPL reserves the right to change or update this policy at any time. Such changes shall be effective immediately upon posting to the website.</p>
<p>Unless stated otherwise, our latest Privacy Notice applies to all information that we have about you and your account. If you have any concern about privacy or grievances at aapkigrocery.com, please contact us with a thorough description and we will try to resolve the issue.</p>
<h2>Contact Information</h2>
<p>Grievance Officer : Mukesh Kumar<br>
aapkigrocery Pvt Ltd,<br>
Tel.: +91 9212153207<br>
Email id: askme@aapkigrocery.com</p>
HTML;

$contactBody = <<<'HTML'
<p>We’d love to hear from you. Reach out to Aapki Grocery for orders, delivery, feedback or support.</p>
<p><b>Email:</b> admin@aapkigrocery.com<br>
<b>Grievance / Support:</b> askme@aapkigrocery.com<br>
<b>Phone:</b> +91 9212153207</p>
<p>Customer service hours: 08:00 AM – 08:00 PM.</p>
HTML;

return [
    ['slug'=>'about-us','title'=>'About Us','body'=>$aboutBody,'meta_description'=>'Aapki Grocery — premium fresh fruits, vegetables, dairy and groceries sourced directly from farms to your door.'],
    ['slug'=>'terms-and-conditions','title'=>'Terms & Conditions','body'=>$termsBody,'meta_description'=>'Aapki Grocery website terms and conditions.'],
    ['slug'=>'privacy-policy','title'=>'Privacy Policy','body'=>$privacyBody,'meta_description'=>'How Aapki Grocery collects, uses and protects your personal information.'],
    ['slug'=>'contact-us','title'=>'Contact Us','body'=>$contactBody,'meta_description'=>'Contact Aapki Grocery support.'],
];
